ProjectSPK/urls.py
from django.contrib import admin
from django.urls import path
from AHP.views import *
from django.contrib.auth.views import LoginView, LogoutView
from django.views.generic import RedirectView

urlpatterns = [
    path('', RedirectView.as_view(url='/masuk/', permanent=True)),
    path('admin/', admin.site.urls),
    path('menu_data/', pendataan, name='pendataan'),
    path('menu_data/menu_edit/<int:id_handphone>', pengeditan, name='pengeditan'),
    path('menu_hitung/', perhitungan, name='perhitungan'),
    path('tambah_data/', tambah_hp, name='penambahan'),
    path('menu_data/hapus/<int:id_handphone>', hapus_data, name='penghapusan'),
    path('masuk/', LoginView.as_view(), name='masuk'),
    path('keluar/', LogoutView.as_view(next_page='masuk'), name='keluar'),
    path('edit_penting/', edit_penting, name='edit_penting'),
    # path('a', edit_penting2, name='a')
]

AHP/models.py
from django.db import models


class design(models.Model):
    nilai = models.IntegerField()
    nama = models.CharField(max_length=20)

    def __str__(self):
        return self.nama


class peforma(models.Model):
    nilai = models.IntegerField()
    nama = models.CharField(max_length=20)

    def __str__(self):
        return self.nama


# class nilai_penting(models.Model):
#     nilai = models.IntegerField()
#     nama = models.CharField(max_length=20)
#
#     def __str__(self):
#         return self.nama


class kepentingan(models.Model):
    design = models.IntegerField()
    storage = models.IntegerField()
    harga = models.IntegerField()
    peforma = models.IntegerField()


class handphone(models.Model):
    merk = models.CharField(max_length=20)
    design = models.ForeignKey(design, on_delete=models.CASCADE, null=True)
    storage = models.IntegerField()
    harga = models.FloatField()
    peforma = models.ForeignKey(peforma, on_delete=models.CASCADE, null=True)

    def __str__(self):
        return self.merk

AHP/forms.py
from django.forms import ModelForm
from django import forms
from AHP.models import *


class form_hp(ModelForm):
    class Meta:
        model = handphone
        fields = '__all__'

        widgets = {
            'merk': forms.TextInput({'class': 'form-control'}),
            'design': forms.Select({'class': 'form-control'}),
            'storage': forms.NumberInput({'class': 'form-control'}),
            'harga': forms.NumberInput({'class': 'form-control'}),
            'peforma': forms.Select({'class': 'form-control'}),
        }


class form_penting(ModelForm):
    class Meta:
        model = kepentingan
        fields = '__all__'

AHP/views.py
from django.shortcuts import render, redirect
from AHP.models import *
from AHP.forms import form_hp, form_penting
from django.contrib import messages
from django.contrib.auth.decorators import login_required
from django.conf import settings
import numpy as np
# from django.http import HttpResponse


@login_required(login_url=settings.LOGIN_URL)
def pendataan(request):
    phone = handphone.objects.all()
    desain = design.objects.all()
    peform = peforma.objects.all()
    penting = kepentingan.objects.get(id=1)
    penting2 = [penting.design, penting.storage, penting.harga, penting.peforma]
    judul = ['Design', 'Storage', 'Harga', 'Peforma']
    konteks = {
        'isi': phone,
        'isi_design': desain,
        'isi_peforma': peform,
        'isi_penting': zip(judul, penting2),
    }
    return render(request, "menu_data.html", konteks)


@login_required(login_url=settings.LOGIN_URL)
def pengeditan(request, id_handphone):
    Handphone = handphone.objects.get(id=id_handphone)
    template = 'menu_edit.html'
    if request.POST:
        form = form_hp(request.POST, instance=Handphone)
        if form.is_valid():
            form.save()
            messages.success(request, "Data Telah Diubah")
            return redirect('pengeditan', id_handphone=id_handphone)
    else:
        form = form_hp(instance=Handphone)
        konteks = {
            'form': form,
            'isi': Handphone
        }
        return render(request, template, konteks)


def premis(a):
    tampung = [1 / 7, 1 / 5, 1 / 3, 1, 3, 5, 7]
    pos = 3
    temp = []
    total = []
    for i in range(len(a)):
        temp2 = []
        tot = 0
        for j in range(len(a)):
            temp2.append(round(tampung[int(pos + ((a[i] - a[j]) / 2))], 3))
            tot += tampung[int(pos + (-1 * (a[i] - a[j]) / 2))]
        temp.append(temp2)
        total.append(round(tot, 3))
    temp.append(total)
    return temp


def normalisasi(a):
    temp = []
    for i in range(len(a) - 1):
        temp2 = []
        tot = 0
        for j in range(len(a) - 1):
            temp2.append(round(a[i][j] / a[4][j], 3))
            tot += a[i][j] / a[4][j]

        temp2.append(round((tot / (len(a) - 1)), 3))
        temp.append(temp2)

    temp.append([round(sum(x), 2) for x in zip(*temp)])
    return temp


def pairwise_kali_Wkriteria(a, b):
    #print(len(a))
    wKriteria = []
    pairwise = []
    #pairwise tanpa total bawah
    for i in range(len(a)-1):
      tamp = []
      for j in range(len(a)-1):
        tamp.append(a[i][j])
      pairwise.append(tamp)
    #print(pairwise)
    # wkriteria
    for i in range(len(b)-1):
      tamp = []
      tamp.append(b[i][4])
      wKriteria.append(tamp)
    #print(wKriteria)
    return pairwise, wKriteria, perkalian_matrix(pairwise, wKriteria)


def perkalian_matrix(a, b):
    temp = np.matmul(a, b)
    temp = np.around(temp, decimals=3)
    return temp


def wKriteria_bagi_pairwiseKaliwKriteria(a, b):
    temp = []
    temp3 = []
    temp2 = []
    temp4 = []
    for i in range(len(a)):
        temp3.append(a[i][0])
        temp4.append(b[i][0])
        temp2.append(round(a[i][0] / b[i][0], 3))
    temp.append(temp3)
    temp.append(temp4)
    temp.append(temp2)
    return temp


def total_wKriteria_bagi_pairwiseKaliwKriteria(a):
    return (np.sum(a[2]))


def hitung_t(a, n):
    return round((a/n), 3)


def hitung_CI(t, n):
    return round((t-n)/(n-1), 3)


def hitung_CR(a,n):
    RIn = {
        2: 0,
        3: 0.58,
        4: 0.9,
        5: 1.12,
        6: 1.24,
        7: 1.32
    }
    return round(a/RIn[n], 3)


def apakah_Konsisten(CR):
    if CR < 0.1:
        return "Konsisten"
    else:
        return "Tidak Konsisten"


def normalisasi_alternatif_desain(alternatif):
    a = np.array(alternatif)
    desain = []
    hasil_d = []
    total = a[:, 0].sum()
    tot_normal = 0
    for i in range (len(alternatif)):
        desain.append(alternatif[i][0])
        hasil_d.append(round(alternatif[i][0]/total, 3))
        tot_normal += hasil_d[i]
    desain.append(total)
    hasil_d.append(round(tot_normal, 2))
    return desain, hasil_d


def normalisasi_alternatif_storage(alternatif):
    a = np.array(alternatif)
    storage = []
    hasil_s = []
    total = a[:,1].sum()
    tot_normal = 0
    for i in range (len(alternatif)):
        storage.append(alternatif[i][1])
        hasil_s.append(round(alternatif[i][1]/total, 3))
        tot_normal += hasil_s[i]
    storage.append(total)
    hasil_s.append(round(tot_normal, 2))
    return storage, hasil_s


def normalisasi_alternatif_harga(alternatif):
    a = np.array(alternatif)
    harga = []
    hasil_h = []
    min = a[:, 2].min()
    tot_normal = 0
    harga_bobot_altenatif = []
    for i in range(len(alternatif)):
        harga_bobot_altenatif.append(round(min/alternatif[i][2], 3))
        harga.append(alternatif[i][2])
    hba = np.array(harga_bobot_altenatif)
    total = hba.sum()
    for i in range(len(harga)):
        hasil_h.append(round(harga_bobot_altenatif[i]/total, 3))
        tot_normal += hasil_h[i]
    harga_bobot_altenatif.append(round(total, 3))
    harga.append(a[:, 2].sum())
    hasil_h.append(round(tot_normal, 2))
    return harga, harga_bobot_altenatif, hasil_h


def normalisasi_alternatif_performa(alternatif):
    a = np.array(alternatif)
    performa = []
    hasil_p = []
    total = a[:, 3].sum()
    tot_normal = 0
    for i in range (len(alternatif)):
        performa.append(alternatif[i][3])
        hasil_p.append(round(alternatif[i][3]/total, 3))
        tot_normal += hasil_p[i]
    performa.append(total)
    hasil_p.append(round(tot_normal, 2))
    return performa, hasil_p


def W_Alternatif_perKriteria(na_d, na_s, na_h, na_p):
    temp = []
    for i in range(len(na_d)):
        temp.append([na_d[i], na_s[i], na_h[i], na_p[i]])
    return temp


def wap_kali_Wkriteria(wap, WK):
    # tampungan sementara menyimpan isi tabel wap tanpa total pada baris ke 4
    temp1 = []
    temp2 = []
    temp3 = []
    for i in range(len(wap)-1):
        temp1.append(wap[i])
    temp2 = perkalian_matrix(temp1, WK)
    for i in range(len(temp2)):
        temp3.append(temp2[i][0])
    # operasi perkalian matriks
    return temp1, temp3


def rank(nama_alternatif, hasil_akhir):
    temp = []
    for i in range(len(nama_alternatif)):
        temp.append([nama_alternatif[i], hasil_akhir[i]])
    temp.sort(reverse= True,key = lambda temp: temp[1])
    return temp


@login_required(login_url=settings.LOGIN_URL)
def perhitungan(request):
    phone = handphone.objects.all()
    mer = handphone.objects.values_list('merk')
    merk = []
    merk1 = []
    for i in range(len(mer)):
        merk.append(mer[i][0])
        merk1.append(mer[i][0])
    merk.append('Total')
    lmerk = (len(merk))
    des = handphone.objects.values_list('design__nilai').order_by('id')
    sto = handphone.objects.values_list('storage')
    har = handphone.objects.values_list('harga')
    pef = handphone.objects.values_list('peforma__nilai').order_by('id')
    penting = kepentingan.objects.get(id=1)
    penting2 = [penting.design, penting.storage, penting.harga, penting.peforma]
    penampungan = []
    for i in range(len(des)):
        penampungan.append([des[i][0], sto[i][0], har[i][0], pef[i][0]])
    hasil = premis(penting2)
    hasil2 = normalisasi(premis(penting2))
    pairwise, wKriteria, hasil3 = pairwise_kali_Wkriteria(hasil, hasil2)
    wbagiaw = wKriteria_bagi_pairwiseKaliwKriteria(hasil3, wKriteria)
    Tot_wbagiaw = total_wKriteria_bagi_pairwiseKaliwKriteria(wbagiaw)
    t = hitung_t(Tot_wbagiaw, len(penting2))
    CI = hitung_CI(t, len(penting2))
    IRn = [[2, 0], [3, 0.58], [4, 0.9], [5, 1.12], [6, 1.24], [7, 1.32]]
    CR = hitung_CR(CI, len(penting2))
    konsisten = apakah_Konsisten(CR)
    d, na_d = normalisasi_alternatif_desain(penampungan)
    s, na_s = normalisasi_alternatif_storage(penampungan)
    h, hba, na_h = normalisasi_alternatif_harga(penampungan)
    p, na_p = normalisasi_alternatif_performa(penampungan)
    wap = W_Alternatif_perKriteria(na_d, na_s, na_h, na_p)
    wap_tanpa_total, hasil_akhir = wap_kali_Wkriteria(wap, wKriteria)
    hasil_rank = rank(merk1, hasil_akhir)
    konteks = {
        'isi': phone,
        'isi_penting': penting2,
        'matriks_utama': penampungan,
        'premis': hasil,
        'normalisasi': hasil2,
        'pairwise': pairwise,
        'wKriteria': wKriteria,
        'hasil3': hasil3,
        'wbagiaw': wbagiaw,
        'Tot_wbagiaw': Tot_wbagiaw,
        't': t,
        'CI': CI,
        'IRn': IRn,
        'CR': CR,
        'konsisten': konsisten,
        'lmerk': lmerk,
        'd': zip(merk, d),
        'na_d': zip(merk, na_d),
        's': zip(merk, s),
        'na_s': zip(merk, na_s),
        'h': zip(merk, h, hba),
        'na_h': zip(merk, na_h),
        'p': zip(merk, p),
        'na_p': zip(merk, na_p),
        'wap': wap,
        'wap_tanpa_total': wap_tanpa_total,
        'hasil_akhir': hasil_akhir,
        'rank': hasil_rank,
    }
    return render(request, "menu_hitung.html", konteks)


@login_required(login_url=settings.LOGIN_URL)
def tambah_hp(request):
    if request.POST:
        form = form_hp(request.POST)
        if form.is_valid():
            form.save()
            form = form_hp()
            pesan = "Data Tersimpan"
            konteks = {
                'form': form,
                'pesan': pesan,
            }
            return render(request, 'tambah_data.html', konteks)

    else:
        form = form_hp()
        konteks = {
            'form': form,
        }
        return render(request, "tambah_data.html", konteks)


@login_required(login_url=settings.LOGIN_URL)
def hapus_data(request, id_handphone):
    phone = handphone.objects.filter(id=id_handphone)
    phone.delete()
    messages.success(request, "Data Telah Dihapus!")
    return redirect('pendataan')


@login_required(login_url=settings.LOGIN_URL)
# def edit_penting(request):

AHP/templates/edit_penting.html
{% extends 'base.html' %}

{% block content %}

    <div class="container" style="margin-top: -20px">
        <div class="row justify-content-center">
            <div class="col-md-3">
{#                {% for pesan in messages %}#}
{#                    {% if pesan %}#}
{#                        <div class="alert alert-success">{{ pesan }}</div>#}
{#                    {% endif %}#}
{#                {% endfor %}#}
                <form action="{% url 'edit_penting'%}" method="post" style="text-align: center; padding: 20px">
                    {% csrf_token %}
                    <h5><label for="id_design">Design</label></h5>
                    <select class="form-control" name="design" id="id_design" style="text-align: center">
                        <option value="{{ isi1 }}" hidden>Kepentingan</option>
                        <option value="1">Tidak Penting</option>
                        <option value="3">Biasa</option>
                        <option value="5">Penting</option>
                        <option value="7">Sangat Penting</option>
                    </select><br>

                    <h5><label for="id_storage">Storage</label></h5>
                    <select class="form-control" name="storage" id="id_storage" style="text-align: center">
                        <option value="{{ isi2 }}" hidden>Kepentingan</option>
                        <option value="1">Tidak Penting</option>
                        <option value="3">Biasa</option>
                        <option value="5">Penting</option>
                        <option value="7">Sangat Penting</option>
                    </select><br>

{#                    <input type="number" name="storage" value="{{ isi2 }}" required id="id_storage">#}
                    <h5><label for="id_harga">Harga</label></h5>
                    <select class="form-control" name="harga" id="id_harga" style="text-align: center">
                        <option value="{{ isi3 }}" hidden>Kepentingan</option>
                        <option value="1">Tidak Penting</option>
                        <option value="3">Biasa</option>
                        <option value="5">Penting</option>
                        <option value="7">Sangat Penting</option>
                    </select><br>
{#                    <input type="number" name="harga" value="{{ isi3 }}" required id="id_harga">#}
                    <h5><label for="id_peforma">Peforma</label></h5>
                    <select class="form-control" name="peforma" id="id_peforma" style="text-align: center">
                        <option value="{{ isi4 }}" hidden>Kepentingan</option>
                        <option value="1">Tidak Penting</option>
                        <option value="3">Biasa</option>
                        <option value="5">Penting</option>
                        <option value="7">Sangat Penting</option>
                    </select><br>
{#                    <input type="number" name="peforma" value="{{ isi4 }}" required id="id_peforma">#}

                    <button class="btn btn-primary">Simpan</button>
                    <a href="../" class="btn btn-danger">Batal</a>
                </form>
            </div>
        </div>
    <div>
{#            <div class="col-md-6">#}
{#                <form action="{% url 'a'%}" method="post">#}
{#                    {% csrf_token %}#}
{#                        {{ form.as_p }}#}
{#                    {% for a in penting %}#}
{#                        {{ forloop.counter }}#}
{#                        <label>{{ a }}</label>#}
{#                        <input type="text" id="fname" name="fname" value="{{ a.nilai_penting }}">#}
{#                        <select name="{{ forloop.counter }}cars" id="{{ forloop.counter }}cars">#}
{#                            {% for b in penting2 %}#}
{#                              <option value="{{ b.id }}{{ b.nama }}">{{ b.nama }}</option>#}
{#                            {% endfor %}#}
{#                        </select>#}
{#                        <br>#}
{#                    {% endfor %}#}
{#                    <button class="btn btn-primary">Simpan</button>#}
{#                    <a href="../" class="btn btn-danger">Batal</a>#}
{#                </form>#}
{#                    {% if pesan %}#}
{#                        <div class="alert alert-success">{{ pesan }}</div>#}
{#                    {% endif %}#}
{#            </div>#}
{#        </div>#}
{#    </div>#}
{#    <div>{{ penting }}</div>#}
{#    <div>{{ penting2 }}</div>#}
{#    <div>{{ request }}</div>#}

{% endblock %}

AHP/templates/menu_data.html
{% extends "base.html" %}

{% block content %}
    <div style="text-align: end; position: fixed; top: 85%; left: 89%; z-index: 100">
        <a class="btn btn-primary col-md-auto" style="margin-bottom: 5px" href="{% url 'penambahan' %}">Tambah Data</a>
        <br>
        <a class="btn btn-success col-md-auto" href="{% url 'perhitungan' %}">Hitung</a>
    </div>

    <div class="container">
        <div class="row justify-content-center col-md-auto">
            {% for pesan in messages %}
                {% if pesan %}
                    <div class="col-md-12 alert alert-success">{{ pesan }}</div>
                {% endif %}
                <br>
            {% endfor %}


        </div>

        <div class="row justify-content-center">
            <div class="col-md-auto">
                <table class="table table-bordered table-striped center table-light">
                    <thead>
                        <tr style="text-align: center">
                            <th>Merk</th>
                            <th>Design</th>
                            <th>Storage (GB)</th>
                            <th>Harga (Juta)</th>
                            <th>Peforma</th>
                            <th>Edit</th>
                        </tr>
                    </thead>
                    <tbody>
                        {% for i in isi %}
                            <tr style="text-align: center">
                                <th style="text-align: left; vertical-align: middle">{{ i.merk }}</th>
                                <th style="vertical-align: middle">{{ i.design }}</th>
                                <th style="vertical-align: middle">{{ i.storage }}</th>
                                <th style="vertical-align: middle">{{ i.harga }}</th>
                                <th style="vertical-align: middle">{{ i.peforma }}</th>
                                <th>
                                    <a class="btn btn-primary" href="{% url 'pengeditan' i.id %}">Ubah</a>
                                    <button type="button" class="btn btn-danger" data-toggle="modal" data-target="#penghapusan-{{ i.id }}">Hapus</button>
                                    <div class="modal fade" id="penghapusan-{{ i.id }}" tabindex="-1" role="dialog" aria-labelledby="exampleModalCenterTitle" aria-hidden="true">
                                        <div class="modal-dialog modal-dialog-centered" role="document">
                                            <div class="modal-content">
                                                <div class="modal-header">
                                                    <h5 class="modal-title" id="exampleModalLongTitle">Konfirmasi</h5>
                                                    <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                                                        <span aria-hidden="true">&times;</span>
                                                    </button>
                                                </div>
                                                <div class="modal-body">
                                                    Apakah anda yakin ingin menghapus data ini ??
                                                </div>
                                                <div class="modal-footer">
                                                    <button type="button" class="btn btn-secondary" data-dismiss="modal">Batal</button>
                                                    <a class="btn btn-danger" href="{% url 'penghapusan' i.id %}">Hapus</a>
                                                </div>
                                            </div>
                                        </div>
                                    </div>
                                </th>
                            </tr>
                        {% endfor %}
                    </tbody>
                </table>
            </div>

            <div class="col-md-2">
                <table class="table table-bordered table-striped center table-primary">
                    <thead>
                        <tr align="center">
                            <th colspan="2">Kepentingan</th>
                        </tr>
                    </thead>
                    <tbody>
                        {% for i, j in isi_penting %}
                        <tr>
                            <th>{{ i }}</th>
                            <th style="text-align: center">{{ j }}</th>
                        </tr>
                        {% endfor %}
                    </tbody>
                </table>
                <div class="row justify-content-center">
{#                    <a class="btn btn-success col-md-3" href="{% url 'edit_penting' %}">Edit</a>#}
{#                    <a class="btn btn-success col-md-3" href="../admin/AHP/kepentingan/">Edit</a>#}
                    <a class="btn btn-outline-primary col-md-auto" href="{% url 'edit_penting' %}">Ubah</a>
                </div>
            </div>

{#            <div class="col-md-auto">#}
{#                <table class="table table-bordered table-striped center table-primary">#}
{#                    <thead>#}
{#                        <tr align="center">#}
{#                            <th colspan="2">Kepentingan</th>#}
{#                        </tr>#}
{#                    </thead>#}
{#                    <tbody>#}
{#                        {% for i in isi_penting %}#}
{#                            <tr>#}
{#                                <th>{{ i }}</th>#}
{#                                <th>{{ i.nilai_penting }}</th>#}
{#                            </tr>#}
{#                        {% endfor %}#}
{#                    </tbody>#}
{#                </table>#}
{#                <div class="row justify-content-center">#}
{#                    <a class="btn btn-success col-md-3" href="{% url 'edit_penting' %}">Edit</a>#}
{#                    <a class="btn btn-success col-md-3" href="../admin/AHP/kepentingan/">Edit</a>#}
{#                </div>#}
{#            </div>#}
        </div>
    </div>



    <div class="container" style="margin-top: 20px">
        <h2 style="text-align: center">Nilai</h2>
        <div class="row justify-content-center">
            <div class="col-md-auto">
                <table class="table table-bordered table-striped center table-danger">
                    <thead>
                        <tr align="center">
                            <th>Merk</th>
                            <th>Design</th>
                            <th>Storage (GB)</th>
                            <th>Harga (Juta)</th>
                            <th>Peforma</th>
                        </tr>
                    </thead>
                    <tbody>
                        {% for i in isi %}
                            <tr style="text-align: center">
                                <th style="text-align: left">{{ i.merk }}</th>
                                <th>{{ i.design.nilai }}</th>
                                <th>{{ i.storage }}</th>
                                <th>{{ i.harga }}</th>
                                <th>{{ i.peforma.nilai }}</th>
                            </tr>
                        {% endfor %}
                    </tbody>
                </table>
            </div>

            <div class="col-md-auto">
                <table class="table table-bordered table-striped center table-warning">
                    <thead>
                        <tr align="center">
                            <th>Design</th>
                            <th>Nilai</th>
                        </tr>
                    </thead>
                    <tbody>
                        {% for i in isi_design %}
                            <tr>
                                <th>{{ i }}</th>
                                <th style="text-align: center">{{ i.nilai }}</th>
                            </tr>
                        {% endfor %}
                    </tbody>
                </table>
            </div>

            <div class="col-md-auto">
                <table class="table table-bordered table-striped center table-success">
                    <thead>
                        <tr align="center">
                            <th>Peforma</th>
                            <th>Nilai</th>
                        </tr>
                    </thead>
                    <tbody>
                        {% for i in isi_peforma %}
                            <tr>
                                <th>{{ i }}</th>
                                <th style="text-align: center">{{ i.nilai }}</th>
                            </tr>
                        {% endfor %}
                    </tbody>
                </table>
            </div>
        </div>
    </div>


{% endblock %}

AHP/templates/menu_edit.html
{% extends 'base.html' %}

{% block content %}

    <div class="container">
        <div class="row justify-content-center">
            <div class="col-md-4">
                {% for pesan in messages %}
                    {% if pesan %}
                        <div class="alert alert-success">{{ pesan }}</div>
                    {% endif %}
                {% endfor %}
                <form action="{% url 'pengeditan' isi.id %}" method="post">
                    {% csrf_token %}
                    {{ form.as_p }}
                    <div style="text-align: center">
                        <button class="btn btn-primary">Simpan</button>
                        <a href="../" class="btn btn-danger">Batal</a>
                    </div>
                </form>
            </div>
        </div>
    </div>

{% endblock %}

AHP/templates/tambah_data.html
{% extends 'base.html' %}

{% block content %}

    <div class="container">
        <div class="row justify-content-center">
            <div class="col-md-4">
                {% if pesan %}
                    <div class="alert alert-success">{{ pesan }}</div>
                {% endif %}
                <form action="" method="post">
                    {% csrf_token %}
                    {{ form.as_p }}
                    <button class="btn btn-primary">Tambah</button>
                    <a href="{% url 'pendataan' %}" class="btn btn-danger">Batal</a>
                </form>
            </div>
        </div>
    </div>


{% endblock %}